apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
      matchLabels:
          component: hello
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: hello
    spec:
      containers:
        - name: hello
          image: sumitchandnani/hello:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    component: hello
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
  